<?php

namespace backend\controllers;

use backend\models\Brand;
use kartik\grid\EditableColumnAction;
use Yii;
use common\models\BrandPolicy;
use backend\models\BrandPolicySearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BrandPolicyController implements the CRUD actions for BrandPolicy model.
 */
class BrandPolicyController extends Controller
{
    public function actions()
    {
        return ArrayHelper::merge(parent::actions(),
            [
                'editValue' => [
                    'class' => EditableColumnAction::className(),
                    'modelClass' => BrandPolicy::className(),
                    'outputValue' => function($model, $attribute, $key, $index) {
                        if ($attribute == 'status') {
                            return '' . BrandPolicy::$statusMap[$model->$attribute];
                        }else if ($attribute == 'brand_id') {
                            return '' . Brand::findOne($model->$attribute)['brand_name'];
                        } else {
                            return '' . $model->$attribute;
                        }
                    },
                    'outputMessage' => function($model, $attribute, $key, $index) {
                        return '';
                    },
                    'showModelErrors' => true,
                    'errorOptions' => ['header' => '']
                ],
            ]); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'update', 'delete', 'create',
                    'editValue',
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all BrandPolicy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BrandPolicySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $brands = Brand::find()->asArray()->all();
        $brands = array_column($brands, 'brand_name', 'brand_id');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'brands' => $brands,
        ]);
    }

    /**
     * Displays a single BrandPolicy model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new BrandPolicy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BrandPolicy();

        $brands = Brand::find()->asArray()->all();
        $brands = array_column($brands, 'brand_name', 'brand_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'brands' => $brands,
            ]);
        }
    }

    /**
     * Updates an existing BrandPolicy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $brands = Brand::find()->asArray()->all();
        $brands = array_column($brands, 'brand_name', 'brand_id');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'brands' => $brands,
            ]);
        }
    }

    /**
     * Deletes an existing BrandPolicy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the BrandPolicy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return BrandPolicy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = BrandPolicy::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
