<?php

namespace backend\controllers;

use backend\models\Goods;
use backend\models\GoodsSearch;
use backend\models\GoodsSupplyInfoUploadForm;
use common\helper\NumberHelper;
use kartik\grid\EditableColumnAction;
use Yii;
use common\models\GoodsSupplyInfo;
use backend\models\GoodsSupplyInfoSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * GoodsSupplyInfoController implements the CRUD actions for GoodsSupplyInfo model.
 */
class GoodsSupplyInfoController extends Controller
{
    public function actions()
    {
        $actionValue = [
            'class' => EditableColumnAction::className(),
            'modelClass' => Goods::className(),
            'outputValue' => function($model, $attribute, $key, $index) {
                $newPrice = $model->$attribute;
                $supplyInfo = $model->supplyInfo;
                if (empty($supplyInfo)) {
                    $supplyInfo = new GoodsSupplyInfo();
                }
                $supplyInfo->supply_price = $newPrice;
                $model->link('supplyInfo', $supplyInfo);
                return NumberHelper::price_format($newPrice);
            },
            'outputMessage' => function($model, $attribute, $key, $index) {
                return '';
            },
            'showModelErrors' => true,
            'errorOptions' => ['header' => '']
        ];
        return ArrayHelper::merge(parent::actions(), [
            'edit-supply-price' => $actionValue
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all GoodsSupplyInfo models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GoodsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $importModel = new GoodsSupplyInfoUploadForm();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'importModel' => $importModel,
        ]);
    }

    /**
     * Displays a single GoodsSupplyInfo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new GoodsSupplyInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new GoodsSupplyInfo();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->goods_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing GoodsSupplyInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->goods_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing GoodsSupplyInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the GoodsSupplyInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return GoodsSupplyInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = GoodsSupplyInfo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionImport() {
        $discountImportModel = new GoodsSupplyInfoUploadForm();

        if (Yii::$app->request->isPost) {
            $discountImportModel->file = UploadedFile::getInstance($discountImportModel, 'file');
            $discountImportModel->import();
        }

        return $this->redirect(['index']);
    }

    public function actionExport() {
        ini_set('memory_limit', '512M');
        ini_set('max_execution_time', 120);
        $searchModel = new GoodsSearch();
        $searchModel->exportSupplyInfo(Yii::$app->request->queryParams);
    }
}
