<?php

namespace backend\controllers;

use common\helper\CacheHelper;
use common\models\IndexKeywords;
use common\models\IndexKeywordsSearch;
use kartik\grid\EditableColumnAction;
use Yii;
use common\models\IndexKeywordsGroup;
use common\models\IndexKeywordsGroupSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * IndexKeywordsGroupController implements the CRUD actions for IndexKeywordsGroup model.
 */
class IndexKeywordsGroupController extends Controller
{
    public function actions()
    {
        $actionEditItemSort = [
            'class' => EditableColumnAction::className(),
            'modelClass' => IndexKeywords::className(),
            'outputValue' => function($model, $attribute, $key, $index) {
                if ($attribute == 'ext') {
                    return IndexKeywords::$extMap[$model->$attribute];
                }
                return $model->$attribute;
            },
            'showModelErrors' => true,
        ];

        $actionEditValue = [
            'class' => EditableColumnAction::className(),
            'modelClass' => IndexKeywordsGroup::className(),
            'outputValue' => function($model, $attribute, $key, $index) {
                if ($attribute == 'scene') {
                    return IndexKeywordsGroup::$sceneMap[$model->$attribute];
                } elseif ($attribute == 'cat_id') {
                    return empty(CacheHelper::getTopGoodsCategoryMap()[$model->$attribute]) ? null : CacheHelper::getTopGoodsCategoryMap()[$model->$attribute];
                }
                return $model->$attribute;
            },
            'showModelErrors' => true,
        ];

        return ArrayHelper::merge(parent::actions(), [
            'edit-keywords-value' => $actionEditItemSort,
            'edit-value' => $actionEditValue,
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all IndexKeywordsGroup models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new IndexKeywordsGroupSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single IndexKeywordsGroup model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new IndexKeywordsGroup model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new IndexKeywordsGroup();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing IndexKeywordsGroup model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $itemSearchModel = new IndexKeywordsSearch();
        $queryParams = Yii::$app->request->queryParams;
        $queryParams['IndexKeywordsSearch']['group_id'] = $id;
        $itemDataProvider = $itemSearchModel->search($queryParams);

        $newKeywords = [];
        for ($i = 0; $i < 3; ++$i) {
            $item = new IndexKeywords();
            $item->is_show = true;
            $newKeywords[] = $item;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'itemSearchModel' => $itemSearchModel,
                'itemDataProvider' => $itemDataProvider,
                'newKeywords' => $newKeywords,
            ]);
        }
    }

    /**
     * Deletes an existing IndexKeywordsGroup model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionCreateKeywords($id) {
        $model = $this->findModel($id);

        $newItemList = [];
        for ($i = 0; $i < 3; ++$i) {
            $item = new IndexKeywords();
            $item->group_id = $model->id;
            $newItemList[] = $item;
        }

        if (IndexKeywords::loadMultiple($newItemList, Yii::$app->request->post()) && IndexKeywords::validateMultiple($newItemList)) {
            foreach ($newItemList as $item) {
                if (!empty($item['title']) && !empty($item['url'])) {
                    $item->save(false);
                }
            }
        }

        $this->redirect(['update', 'id' => $id]);
    }

    public function actionDeleteKeywords($id) {
        $item = IndexKeywords::findOne($id);
        $groupId = $item['group_id'];
        $item->delete();
        $this->redirect(['/index-keywords-group/update', 'id' => $groupId]);
    }

    /**
     * Finds the IndexKeywordsGroup model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return IndexKeywordsGroup the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = IndexKeywordsGroup::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
