<?php

namespace backend\controllers;

use backend\models\Goods;
use kartik\grid\EditableColumnAction;
use Yii;
use common\models\NewArrivedGoods;
use common\models\NewArrivedGoodsSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewArrivedGoodsController implements the CRUD actions for NewArrivedGoods model.
 */
class NewArrivedGoodsController extends Controller
{
    public function actions()
    {

        $actionEditValue = [
            'class' => EditableColumnAction::className(),
            'modelClass' => NewArrivedGoods::className(),
            'outputValue' => function($model, $attribute, $key, $index) {
                if ($attribute == 'goods_id') {
                    return empty(Goods::getGoodsMap()[$model->$attribute]) ? null: Goods::getGoodsMap()[$model->$attribute];
                }
                return $model->$attribute;
            },
            'showModelErrors' => true,
        ];

        return ArrayHelper::merge(parent::actions(), [
            'edit-value' => $actionEditValue,
        ]); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all NewArrivedGoods models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new NewArrivedGoodsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single NewArrivedGoods model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new NewArrivedGoods model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new NewArrivedGoods();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing NewArrivedGoods model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing NewArrivedGoods model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the NewArrivedGoods model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return NewArrivedGoods the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = NewArrivedGoods::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
