<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/16 0016
 * Time: 12:05
 */

namespace common\widgets;


class ActionColumn extends \yii\grid\ActionColumn
{
    public function renderFooterCell()
    {
//        $res = parent::renderFooterCell(); // TODO: Change the autogenerated stub
        return $this->renderFooterCellContent();
    }

    protected function renderFooterCellContent()
    {
        return trim($this->footer) !== '' ? $this->footer : '';
    }
}