<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/12 0012
 * Time: 9:48
 */

namespace common\widgets;


class DataColumn extends \yii\grid\DataColumn
{
    public $headerFormat;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function renderDataCellContent($model, $key, $index)
    {
        $res = parent::renderDataCellContent($model, $key, $index); // TODO: Change the autogenerated stub
        return $res;
    }


    public function renderHeaderCellContent()
    {
//        if(in_array($this->headerFormat, ['raw', 'text', 'html'])) {
//            $res = $this->grid->formatter->format(, $this->headerFormat);
//        }
//        else {
            $res = parent::renderHeaderCellContent(); // TODO: Change the autogenerated stub
//        }
        return $res;
    }

    public function renderDataCell($model, $key, $index)
    {
        $res = parent::renderDataCell($model, $key, $index); // TODO: Change the autogenerated stub
        return $res;
    }

    public function renderHeaderCell()
    {
        $res = parent::renderHeaderCell(); // TODO: Change the autogenerated stub
        return $res;
    }

    public function renderFooterCell()
    {
//        $res = parent::renderFooterCell(); // TODO: Change the autogenerated stub
        return $this->renderFooterCellContent();
    }

    protected function renderFooterCellContent()
    {
        return trim($this->footer) !== '' ? $this->footer : '';
    }
}