<?php

namespace common\models;

use common\helper\DateTimeHelper;
use Yii;

/**
 * This is the model class for table "o_coupon_record".
 *
 * @property integer $coupon_id
 * @property integer $event_id
 * @property integer $rule_id
 * @property string $coupon_sn
 * @property string $user_id
 * @property integer $received_at
 * @property integer $used_at
 * @property integer $created_by
 * @property integer $status
 * @property string $group_id
 * @property string $start_time
 * @property string $end_time
 */
class CouponRecord extends \yii\db\ActiveRecord
{
    const COUPON_STATUS_UNUSED  = 0;
    const COUPON_STATUS_USED    = 1;
    const COUPON_STATUS_EXPIRED = 2;

    public static $couponStatusMap = [
        self::COUPON_STATUS_UNUSED  => '未使用',
        self::COUPON_STATUS_USED    => '已使用',
        self::COUPON_STATUS_EXPIRED => '已过期',
    ];
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'o_coupon_record';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['event_id', 'rule_id', 'coupon_sn', 'created_by'], 'required'],
            [['event_id', 'rule_id', 'received_at', 'used_at', 'status', 'created_by'], 'integer'],
            [['start_time', 'end_time'], 'string'],
            [['coupon_sn'], 'string', 'max' => 10],
            [['group_id'], 'string', 'max' => 22],
            [['user_id', 'status', 'used_at'], 'default', 'value' => 0],
            [['start_time', 'end_time'], 'default', 'value' => '0000-00-00 00:00:00'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'coupon_id'     => '优惠券流水号',
            'event_id'      => '优惠券活动ID',
            'rule_id'       => '优惠券规则ID',
            'coupon_sn'     => '优惠券编号',
            'user_id'       => '拥有者',
            'received_at'   => '获取时间',
            'used_at'       => '使用时间',
            'group_id'      => '总单号',
            'created_by'    => '最后操作人',
            'status'        => '状态',
            'start_time'    => '可用时段开始时间',
            'end_time'      => '可用时段结束时间',
        ];
    }

    /**
     * 如果用户之前没有操作人，则最后操作人为当前用户
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            //  商品最后操作人 即 操作绑定券的人
            if (!empty(Yii::$app->user) && !empty(Yii::$app->user->identity)) {
                if (isset(Yii::$app->user->identity->id)) {
                    $this->created_by = Yii::$app->user->identity->id;
                }
            }

            //  优惠券绑定用户时 判定是否需要更新优惠券的生效时段
            if (empty($this->oldAttributes['user_id']) && !empty($this->user_id)) {
                $fullCutRule = FullCutRule::find()
                    ->joinWith('event')
                    ->where([FullCutRule::tableName().'.rule_id' => $this->rule_id])
                    ->one();
                if (!empty($fullCutRule)) {
                    if ($fullCutRule->term_of_validity > 0) {
                        $this->start_time = date('Y-m-d H:i:s');
                        $this->end_time = date('Y-m-d H:i:s', time() + $fullCutRule->term_of_validity);
                    } else {
                        $this->start_time = $fullCutRule->event->start_time;
                        $this->end_time = $fullCutRule->event->end_time;
                    }
                    $this->received_at = DateTimeHelper::gmtime();

                    //通过 加红点 提示去领劵
                    $redDot = RedDot::find()->where(['user_id' => $this->user_id])->one();
                    if(empty($redDot)) {
                        $redDot = new RedDot();
                        $redDot->user_id =  $this->user_id;
                        $redDot->save();
                    }
                }

            }

            return true;
        } else {
            return false;
        }
        // TODO: Change the autogenerated stub
    }

    /**
     * 优惠券绑定用户时 判定是否需要更新优惠券的生效时段
     * @param bool $insert
     * @param array $changedAttributes
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes);
    }

    /**
     * 关联 优惠券所属的用户
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['user_id' => 'user_id']);
    }


    /**
     * 关联 优惠券的发行者
     * @return \yii\db\ActiveQuery
     */
    public function getCreater()
    {
        return $this->hasOne(Users::className(), ['user_id' => 'created_by']);
    }

    /**
     * 关联优惠券对应的活动
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(Event::className(), ['event_id' => 'event_id']);
    }

    /**
     * 关联优惠券对应的活动
     * @return \yii\db\ActiveQuery
     */
    public function getFullCutRule()
    {
        return $this->hasOne(FullCutRule::className(), ['rule_id' => 'rule_id']);
    }

    /**
     * 关联参与优惠券活动的商品
     * @return \yii\db\ActiveQuery
     */
    public function getEventToGoods()
    {
        return $this->hasMany(EventToGoods::className(), ['event_id' => 'event_id']);
    }

    /**
     * 关联使用指定优惠券的总单
     * @return \yii\db\ActiveQuery
     */
    public function getOrderGroup()
    {
        return $this->hasOne(OrderGroup::className(), ['group_id' => 'group_id']);
    }

    /**
     * 修正已过期的优惠券状态
     * @param $userId
     */
    public static function setExpiredCoupon($userId)
    {
        //  获取用户的优惠券列表前修正过期优惠券的状态
        $dateTime = date('Y-m-d H:i:s');
        CouponRecord::updateAll(
            ['status' => CouponRecord::COUPON_STATUS_EXPIRED],
            [
                'and',
                ['user_id' => $userId],
                ['status' => CouponRecord::COUPON_STATUS_UNUSED],
                ['<', 'end_time', $dateTime],
            ]
        );
    }
}
