<?php

namespace common\models;

use common\behaviors\UploadImageBehavior;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "o_goods_gallery".
 *
 * @property string $img_id
 * @property string $goods_id
 * @property string $img_url
 * @property string $img_desc
 * @property string $thumb_url
 * @property string $img_original
 */
class GoodsGallery extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [];
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            //  商品显示图和缩略图 路径修正
            if (!empty($this->img_original)) {
                $pathParts = pathinfo($this->img_original);
                $dirname = $pathParts['dirname'];
                $basename = $pathParts['basename'];
                $this->img_url     = $dirname.'/preview-'.$basename;
                $this->thumb_url   = $dirname.'/thumb-'.$basename;
            }
            return true;
        } else {
            return false;
        }
        // TODO: Change the autogenerated stub
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'o_goods_gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['goods_id'], 'integer'],
            [['img_url', 'img_desc', 'thumb_url'], 'string', 'max' => 255],
            ['img_original', 'required', 'on' => 'create'],
            [
                'img_original',
                'image',
                'extensions' => 'jpg, jpeg, gif, png',
                'on' => ['insert', 'update']
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'img_id' => '图片ID',
            'goods_id' => '商品ID',
            'img_url' => '默认图路径',
            'img_desc' => '图片描述',
            'thumb_url' => '缩略图',
            'img_original' => '原图',
        ];
    }

    /**
     * 关联商品
     * @return \yii\db\ActiveQuery
     */
    public function getGoods()
    {
        return $this->hasOne(Goods::className(), ['goods_id' => 'goods_id']);
    }
}
