<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "o_spu".
 *
 * @property integer $id
 * @property string $name
 */
class Spu extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'o_spu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * 删除SPU 之前 检验是否有关联商品
     * 没有关联商品的SPU 才可以删除
     * @return bool
     */
    public function beforeDelete()
    {
        $skuGoods = Goods::find()->where(['spu_id' => $this->id])->one();
        if (!empty($skuGoods)) {
            Yii::$app->session->setFlash('error', '当前SPU关联有商品，不可以删除');
        } else {
            return parent::beforeDelete(); // TODO: Change the autogenerated stub
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'SPU名称',
        ];
    }

    /**
     * 关联 SKU
     * @return \yii\db\ActiveQuery
     */
    public function getGoods()
    {
        return $this->hasMany(Goods::className(), ['spu_id' => 'id']);
    }

    /**
     * 获取SPU id => name 映射
     * @return array
     */
    public static function spuMap()
    {
        $spuMap = [];
        $map = self::find()->all();

        if (!empty($map)) {
            foreach ($map as $spu) {
                $spuMap[$spu->id] = '['.$spu->id.']'.$spu->name;
            }
        }

        return $spuMap;
    }
}
