<?php

namespace backend\models;

use Yii;
use yii\base\Model;
use yii\helpers\VarDumper;

class BrandDiscountUploadForm extends Model
{
    public $file;

    public function attributeLabels()
    {
        return [
            'file' => '品牌数据导入（excel文件）'
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['file'], 'file', 'skipOnEmpty' => false],
        ];
    }

    public function import() {
        if($this->validate()) {
            if ($this->file->extension != 'xlsx' && $this->file->extension != 'xls') {
                return false;
            }
            $filePath = 'uploads/' . $this->file->baseName . '.' . $this->file->extension;
            $this->file->saveAs('uploads/' . $this->file->baseName . '.' . $this->file->extension);
            $data = \moonland\phpexcel\Excel::import($filePath);
            if(!empty($data)) {
                foreach ($data as $brandDiscountInfo) {
                    if(empty($brandDiscountInfo['brand_id'])) {
                        continue;
                    }
                    $brand = Brand::findOne([
                        'brand_id' => $brandDiscountInfo['brand_id']
                    ]);
                    if($brand) {
                        if (!empty($brandDiscountInfo['discount']) && is_numeric($brandDiscountInfo['discount'])) {
                            $brand->discount = ''.$brandDiscountInfo['discount'];
                        }
                        if (!empty($brandDiscountInfo['sort_order']) && is_numeric($brandDiscountInfo['sort_order'])) {
                            $brand->sort_order = (int)$brandDiscountInfo['sort_order'];
                        }
                        if (!empty($brandDiscountInfo['character']) && is_string($brandDiscountInfo['character'])) {
                            $brand->character = trim($brandDiscountInfo['character']);
                        }
                        if (!empty($brandDiscountInfo['brand_area']) && is_string($brandDiscountInfo['brand_area'])) {
                            $brand->brand_area = trim($brandDiscountInfo['brand_area']);
                        }
                        if (!empty($brandDiscountInfo['brand_tag'])) {
                            $tags = explode(',', $brandDiscountInfo['brand_tag']);
                            $realValue = '';
                            if (count($tags) > 0) {
                                foreach ($tags as $key => $value) {
                                    if (is_numeric($value)) {
                                        $intValue = (int) $value;
                                        if ($key > 0) {
                                            $realValue .= ',';
                                        }
                                        $realValue .= $intValue;
                                    }
                                }
                            }
                            $brand->brand_tag = $realValue;
                        }
                        if (!$brand->save()) {
                            $message = Yii::$app->session->getFlash('error', '');
                            $message .= VarDumper::export($brand->errors);
                            Yii::$app->session->setFlash('error', $message);
                        }
                    }
                }
            }
            else {
                unlink($filePath);
                return false;
            }
            unlink($filePath);
            return true;
        }
        Yii::$app->session->setFlash('error', VarDumper::export($this->errors));
        return false;
    }
}