<?php

namespace backend\models;

use Yii;
use yii\base\Model;
use yii\helpers\VarDumper;

class CategoryUploadForm extends Model
{
    public $file;

    public function attributeLabels()
    {
        return [
            'file' => '品牌数据导入（excel文件）'
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['file'], 'file', 'skipOnEmpty' => false],
        ];
    }

    public function import() {
        if($this->validate()) {
            if ($this->file->extension != 'xlsx' && $this->file->extension != 'xls') {
                return false;
            }
            $filePath = 'uploads/' . $this->file->baseName . '.' . $this->file->extension;
            $this->file->saveAs('uploads/' . $this->file->baseName . '.' . $this->file->extension);
            $data = \moonland\phpexcel\Excel::import($filePath);
            if(!empty($data)) {
                foreach ($data as $categoryInfo) {
                    if (!empty($categoryInfo['cat_id'])) {
                        $category = new Category();
                        $category->cat_id = $categoryInfo['cat_id'];
                        $category->sort_order = 125;
                        $category->show_in_nav = 0;
                        $category->is_show = 1;
                        $category->cat_name = empty($categoryInfo['cat_name']) ? '': $categoryInfo['cat_name'];
                        $category->parent_id = $categoryInfo['parent_id'];
                        $category->save();
                    }
                }
            }
            else {
                unlink($filePath);
                return false;
            }
            unlink($filePath);
            return true;
        }
        Yii::$app->session->setFlash('error', VarDumper::export($this->errors));
        return false;
    }
}