<?php
/**
 * Created by PhpStorm.
 * User: clark
 * Date: 2016/11/8
 * Time: 22:04
 */

namespace backend\models;

class GoodsAttr extends \common\models\GoodsAttr
{

    public $region; //  地区 对应id
    public $effect;
    public $sample; //  物料

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['region', 'effect', 'sample'], 'safe'],
            [['region', 'effect', 'sample'], 'string'],
        ]); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'region' => '产地',
            'effect' => '功效',
            'sample' => '物料配比',
        ]); // TODO: Change the autogenerated stub
    }

    public static function getUpdateSql($goods_id, $attr_id, $attr_value, $is_update) {
        if ($is_update) {
            $sql = ' UPDATE '.GoodsAttr::tableName().
                ' SET attr_value = \''.$attr_value.'\''.
                ' WHERE goods_id = '.$goods_id.' AND attr_id = '.$attr_id;
        } else {
            $sql = ' INSERT INTO '.GoodsAttr::tableName().
                ' (goods_id, attr_id, attr_value, attr_price) VALUES '.
                ' ('.$goods_id.', '.$attr_id.', \''.$attr_value.'\', 0)';
        }

        return $sql;
    }
}