<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/8 0008
 * Time: 15:58
 */

namespace backend\models;

use common\models\GoodsSupplyInfo;
use Yii;
use yii\base\Model;
use yii\helpers\VarDumper;

class GoodsSupplyInfoUploadForm extends Model
{
    public $file;

    public function attributeLabels()
    {
        return [
            'file' => '服务商折扣计算价（excel文件）'
        ]; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['file'], 'file', 'skipOnEmpty' => false],
        ];
    }

    /**
     * 成本价导入
     * @return bool
     */
    public function import() {
        if($this->validate()) {
            ini_set('max_execution_time', 120);
            ini_set('memory_limit', '1G');
            if ($this->file->extension != 'xlsx' && $this->file->extension != 'xls') {
                return false;
            }
            $filePath = 'uploads/' . $this->file->baseName . '.' . $this->file->extension;
            $this->file->saveAs('uploads/' . $this->file->baseName . '.' . $this->file->extension);
            $data = \moonland\phpexcel\Excel::import($filePath);

            unlink($filePath);

            $errorMsg = '';

            if(!empty($data)) {
                foreach ($data as $goodsSupplyInfo) {
                    if(empty($goodsSupplyInfo['goods_id']) || empty($goodsSupplyInfo['supply_price'])) {
                        continue;
                    }
                    $goods = Goods::find()->where([
                        'goods_id' => $goodsSupplyInfo['goods_id']
                    ])->with([
                        'supplyInfo'
                    ])->one();

                    if (empty($goods)) {
                        $errorMsg .= ''. $goodsSupplyInfo['goods_id']. '没有找到匹配的商品ID'. PHP_EOL;
                        continue;
                    }

                    $supplyInfo = $goods->supplyInfo;
                    if (empty($supplyInfo)) {
                        $supplyInfo = new GoodsSupplyInfo();
                    }
                    $supplyInfo->supply_price = $goodsSupplyInfo['supply_price'];

                    if ($supplyInfo->isNewRecord) {
                        $goods->link('supplyInfo', $supplyInfo);
                    }
                    else {
                        $supplyInfo->save();
                    }
                }
            }
            else {
                return false;
            }
            return true;
        }
        Yii::$app->session->setFlash('error', VarDumper::export($this->errors));
        return false;
    }
}