<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/12/23 0023
 * Time: 19:19
 */

namespace backend\models;


use yii\helpers\ArrayHelper;

class MoreGoodsGallery extends GoodsGallery
{
    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            ['img_original', 'required', 'on' => 'insert'],
        ]); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [

        ];
    }

}