<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/8 0008
 * Time: 11:02
 */

namespace backend\models;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "o_order_goods".
 *
 * @property integer $waitForShippingNum
 * @property integer $shippingNum
 */
class OrderGoods extends \common\models\OrderGoods
{
    public $waitForShippingNum;
    public $shippingNum;

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            ['shippingNum', 'safe'],
        ]); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'shippingNum' => '发货数量',
        ]); // TODO: Change the autogenerated stub
    }
}