<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/20 0020
 * Time: 16:01
 */

namespace service\assets;

use Yii;
use yii\web\AssetBundle;

class LoginAsset extends AssetBundle
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $customCss = 'http://adminjs.xiaomei360.com/components/service/login/login.css?version='. Yii::$app->params['r_version'];
        $this->css = [
            $customCss,
        ];

        $customJs[] = 'http://adminjs.xiaomei360.com/lib/lib.js?version='. Yii::$app->params['r_version'];
        $customJs[] = 'http://adminjs.xiaomei360.com/app/service/login.js?version='. Yii::$app->params['r_version'];
        $this->js = $customJs;
    }
}