<?php

namespace service\assets;

use Yii;
use yii\web\AssetBundle;

class ServicerDivideDetailAsset extends AssetBundle
{
    public $depends = [
        'service\assets\BaseAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $customCss = 'http://adminjs.xiaomei360.com/components/service/orderDetail/orderDetail.css?version='. Yii::$app->params['r_version'];
        $this->css = [
            $customCss,
        ];

        $this->js = [
            'http://adminjs.xiaomei360.com/lib/lib_base.js?version='. Yii::$app->params['r_version'],
            'http://adminjs.xiaomei360.com/lib/grid.js?version='. Yii::$app->params['r_version'],
            'http://adminjs.xiaomei360.com/app/service/orderDetail.js?version='. Yii::$app->params['r_version'],
        ];
    }
}