<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/7 0007
 * Time: 21:33
 */
namespace service\assets;

use Yii;
use yii\web\AssetBundle;

class ServicerStoreUser extends AssetBundle
{
    public $depends = [
        'service\assets\BaseAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $customCss = 'http://adminjs.xiaomei360.com/lib/lib_base.js?version='. Yii::$app->params['r_version'];
        $this->css = [
            $customCss,
        ];

        $customJs[] = 'http://adminjs.xiaomei360.com/lib/grid.js?version='. Yii::$app->params['r_version'];
        $customJs[] = 'http://adminjs.xiaomei360.com/app/service/storeMange.js?version='. Yii::$app->params['r_version'];
        $this->js = $customJs;
    }
}