<?php

namespace service\assets;

use Yii;
use yii\web\AssetBundle;

class UserUncheckedAsset extends AssetBundle
{
    public $depends = [
        'service\assets\BaseAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $r_version = Yii::$app->params['r_version'];
        $customCss = 'http://adminjs.xiaomei360.com/components/service/userMange/userMange.css?version='. $r_version;
        $this->css = [
            $customCss,
        ];

        $customJs[] = 'http://adminjs.xiaomei360.com/lib/dataTables.js?version='. $r_version;
        $customJs[] = 'http://adminjs.xiaomei360.com/app/service/storeCheck.js?version='. $r_version;
        $this->js = $customJs;
    }
}