<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017-08-23
 * Time: 11:01
 */

namespace pc\widgets;


class TopHeader extends BaseWidget
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

    }
}