<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/19 0019
 * Time: 14:04
 */

namespace service\controllers;

use common\helper\NumberHelper;
use common\models\CashRecord;
use Yii;
use common\helper\ServicerDivideHelper;
use common\models\OrderInfo;
use yii\db\Query;
use yii\helpers\VarDumper;
use yii\web\Controller;

class XmController extends Controller
{
    public $orderDoneNum;
    public $orderReturnNum;

    public $divideAll;
    public $cashAll;
//    public $divideEnable;
//    public $divideFrozen;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $query = new Query();
        //只算已流程终止的
        $this->orderDoneNum = $query->select(['COUNT(*) doneNum'])->from(\common\models\OrderInfo::tableName())->where(['order_sn'=>\common\models\OrderInfo::ORDER_STATUS_REALLY_DONE])->one()['doneNum'];

        //只算已流程终止的
        $this->orderReturnNum = $query->select(['COUNT(*) returnNum'])->from(\common\models\OrderInfo::tableName())->where(['order_sn' =>[\common\models\OrderInfo::ORDER_STATUS_RETURNED_DONE, \common\models\OrderInfo::ORDER_STATUS_REFUNDED_DONE]])->one()['returnNum'];

        $mineAmounts = ServicerDivideHelper::getAllTotalDivideAmount([Yii::$app->user->identity['user_id']], [OrderInfo::ORDER_STATUS_CONFIRMED, OrderInfo::ORDER_STATUS_SPLITED, OrderInfo::ORDER_STATUS_DONE, OrderInfo::ORDER_STATUS_REALLY_DONE]);
        $mineAmount = $mineAmounts[0]['total_all'];
        if($mineAmount == null) {
            $mineAmount = 0;
        }
        $this->divideAll = NumberHelper::price_format($mineAmount);

//        $mineEnableAmounts = ServicerDivideHelper::getAllTotalDivideAmount([Yii::$app->user->identity['user_id']], OrderInfo::ORDER_STATUS_REALLY_DONE);
//        $mineEnableAmount = $mineEnableAmounts[0]['total_all'];
//        if($mineEnableAmount == null) {
//            $mineEnableAmount = 0;
//        }
//        $this->divideEnable = NumberHelper::price_format($mineEnableAmount);

//        $mineUnableAmounts = ServicerDivideHelper::getAllTotalDivideAmount([Yii::$app->user->identity['user_id']], [OrderInfo::ORDER_STATUS_CONFIRMED, OrderInfo::ORDER_STATUS_SPLITED, OrderInfo::ORDER_STATUS_DONE, OrderInfo::ORDER_STATUS_REALLY_DONE]);
//        $mineUnableAmount = $mineUnableAmounts[0]['total_all'];
//        if($mineUnableAmount == null) {
//            $mineUnableAmount = 0;
//        }
//        $this->divideFrozen = NumberHelper::price_format($mineUnableAmount);

        $totalCash = CashRecord::totalCash();
        $totalCash = empty($totalCash) ? 0.00: $totalCash;
        $this->cashAll = NumberHelper::price_format($totalCash);

        Yii::info('Controller初始化 cur_user = '. VarDumper::export(Yii::$app->user->identity). ', divideAll = '. $this->divideAll.', cashAll = '. $this->cashAll);
    }
}