<?php
/**
 * Created by PhpStorm.
 * User: HongXunPan
 * Date: 2017/8/17
 * Time: 22:27
 */

namespace data\controllers;

use yii\web\Controller;
use Yii;
use yii\web\Response;

class DataBaseController extends Controller
{
    public static function allowedDomains()
    {
        return [
            '*'
        ];
    }

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'corsFilter' => [
                'class' => \yii\filters\Cors::className(),
                'cors' => [
                    'Origin' => ['http://data.xiaomei360.com'],
                    'Access-Control-Request-Method' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS'],
                    'Access-Control-Request-Headers' => ['*'],
                    'Access-Control-Allow-Credentials' => true,
                    'Access-Control-Max-Age' => 86400,
                    'Access-Control-Expose-Headers' => [],
                    'Content-Type' => 'application/json; charset utf-8',
                ],
            ],
        ]);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }
}