<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/15
 * Time: 16:13
 */

namespace brand\assets;

use yii\web\AssetBundle;
use \Yii;

class BrandBaseAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $customCss = 'http://adminjs.xiaomei360.com/lib/base.css?version='. Yii::$app->params['r_version'];
        $this->css = [
            $customCss,
        ];

        $customJs[] = 'http://adminjs.xiaomei360.com/lib/lib_base.js?version='. Yii::$app->params['r_version'];
        $this->js = $customJs;
    }

    public static function addOrderCss($view)
    {
        $order_css = 'http://adminjs.xiaomei360.com/components/supplier/order/order.css?version='.Yii::$app->params['r_version'];
        $view->registerCssFile($order_css, [BrandBaseAsset::className(), 'depends' => 'brand\assets\BrandBaseAsset']);
    }
}