<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/6/15
 * Time: 17:07
 */

namespace brand\assets;

use \Yii;

class OrderAsset extends BrandBaseAsset
{
    public $depends = [
        'brand\assets\BrandBaseAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $r_version = Yii::$app->params['r_version'];
        $order_css = 'http://adminjs.xiaomei360.com/components/supplier/order/order.css?version='.$r_version;
        $this->css = [
            $order_css,
        ];


        $orderJs[] = 'http://adminjs.xiaomei360.com/lib/lib_base.js?version='. $r_version;
        $orderJs[] = 'http://adminjs.xiaomei360.com/lib/grid.js?version='. $r_version;
        $orderJs[] = 'http://adminjs.xiaomei360.com/app/supplier/order.js?version='. $r_version;
        $this->js = $orderJs;
    }
}